### ISSUE TITLE
Proper location for the binary

### ISSUE THREAD

**Issue by cmsj** [jridgewell/Unlock#18]
It seems to be fairly unconventional to store the unlock binary in /Library/LaunchDaemons/. Given that homebrew sets crazy permissions on many /usr/local/ directories, and all of /System and /sbin are locked down by SIP, perhaps /Library/PrivilegedHelperTools/ would be a reasonable place to put the binary?

**Comment by jridgewell** [comment]
> Given that homebrew sets crazy permissions on many /usr/local/ directories

We run as `root` during install, so that shouldn't be an issue. Want to open a PR?

**Comment by tjluoma** [comment]
Installers that write to /usr/local/bin/ work fine with Homebrew as long as it doesn't change ownership or permissions of that directory.

**Comment by cmsj** [comment]
To be clear, I'm not saying that homebrew's permissions make it tricky to install in /usr/local, I'm saying that they make it inappropriate to install anything in there which will be run as root, on boot :)
