### ISSUE TITLE
Wrong -T path

### ISSUE THREAD

**Issue by petter-** [jridgewell/Unlock#21]
It seems that you missed a path on the last commit.

line 40
		-w "${password}" -T "" -T "/Library/LaunchDaemons/name.ridgewell.unlock" -U "/Library/Keychains/System.keychain"

Should be 
		-w "${password}" -T "" -T "/Library/PrivilegedHelperTools/name.ridgewell.unlock" -U "/Library/Keychains/System.keychain"

right?

regards

**Comment by jridgewell** [comment]
Thanks!
