### ISSUE TITLE
My Harddrive is locked!!!

### ISSUE THREAD

**Issue by willis02** [jridgewell/Unlock#29]
Hi everyone,
I recently have installed Ubuntu onto my Laptop that already has Windows 10 on it as well.
And now my hard drive is locked (bitlocker2)
Any help would be much appreciated.
Thanks Heaps
Will

![Screenshot from 2021-05-24 09-49-19](https://user-images.githubusercontent.com/84744576/119407334-2fa39500-bd38-11eb-9715-4ba3001d4302.png)
![Screenshot from 2021-05-24 09-48-50](https://user-images.githubusercontent.com/84744576/119407343-3205ef00-bd38-11eb-9f90-2b49329bd843.png)

**Comment by jridgewell** [comment]
This project is for Apple's old Core Storage filesystem format.
